"""interview, knowledge, memory, providers, procedures

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-03 12:40:07.324691
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedures',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=True),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('current_step_key', sa.String(length=64), nullable=True),
    sa.Column('waiting_for', sa.String(length=64), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procedures'))
    )
    with op.batch_alter_table('procedures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procedures_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_procedures_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_procedures_subject_id'), ['subject_id'], unique=False)

    op.create_table('project_usage_daily',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_usage_daily')),
    sa.UniqueConstraint('project_id', 'date', 'provider_id', name='uq_usage_day')
    )
    with op.batch_alter_table('project_usage_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_usage_daily_project_id'), ['project_id'], unique=False)

    op.create_table('procedure_steps',
    sa.Column('procedure_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('supervisor_decision', sa.JSON(), nullable=True),
    sa.Column('next_key', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('llm_usage', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], name=op.f('fk_procedure_steps_procedure_id_procedures'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procedure_steps'))
    )
    with op.batch_alter_table('procedure_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procedure_steps_procedure_id'), ['procedure_id'], unique=False)

    op.create_table('data_sources',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('access_notes', sa.Text(), nullable=True),
    sa.Column('schema', sa.JSON(), nullable=False),
    sa.Column('sample_refs', sa.JSON(), nullable=False),
    sa.Column('sensitivity', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_data_sources_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sources'))
    )
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_sources_project_id'), ['project_id'], unique=False)

    op.create_table('llm_providers',
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('adapter', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('models', sa.JSON(), nullable=False),
    sa.Column('api_key_encrypted', sa.String(length=2000), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('purposes', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('health', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_llm_providers_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_providers'))
    )
    with op.batch_alter_table('llm_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_providers_project_id'), ['project_id'], unique=False)

    op.create_table('skills',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('development_state', sa.String(length=16), nullable=False),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspend_note', sa.Text(), nullable=True),
    sa.Column('current_published_version_id', sa.String(length=36), nullable=True),
    sa.Column('latest_version_id', sa.String(length=36), nullable=True),
    sa.Column('forked_from_skill_id', sa.String(length=36), nullable=True),
    sa.Column('forked_from_version_id', sa.String(length=36), nullable=True),
    sa.Column('fork_kind', sa.String(length=24), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('install_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_skills_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_skills_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills')),
    sa.UniqueConstraint('project_id', 'name', name='uq_skill_project_name')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_project_id'), ['project_id'], unique=False)

    op.create_table('interview_sessions',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('knowledge_id', sa.String(length=36), nullable=True),
    sa.Column('procedure_id', sa.String(length=36), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('token_usage', sa.JSON(), nullable=False),
    sa.Column('pending_question', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_interview_sessions_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_interview_sessions_skill_id_skills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_interview_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_sessions'))
    )
    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_sessions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interview_sessions_skill_id'), ['skill_id'], unique=False)

    op.create_table('knowledge_docs',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('doc', sa.JSON(), nullable=False),
    sa.Column('completeness', sa.JSON(), nullable=False),
    sa.Column('derived_from_session_id', sa.String(length=36), nullable=True),
    sa.Column('frozen', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_knowledge_docs_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_docs'))
    )
    with op.batch_alter_table('knowledge_docs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_docs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_docs_skill_id'), ['skill_id'], unique=False)

    op.create_table('skill_memory_entries',
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('structured', sa.JSON(), nullable=False),
    sa.Column('step_key', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('source_ref', sa.String(length=36), nullable=True),
    sa.Column('skill_version_id', sa.String(length=36), nullable=True),
    sa.Column('author_user_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('superseded_by_id', sa.String(length=36), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_skill_memory_entries_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_memory_entries'))
    )
    with op.batch_alter_table('skill_memory_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_memory_entries_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_memory_entries_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_memory_entries_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_memory_entries_step_key'), ['step_key'], unique=False)

    op.create_table('interview_messages',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('fk_interview_messages_session_id_interview_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_messages'))
    )
    with op.batch_alter_table('interview_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_messages_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_messages_session_id'))

    op.drop_table('interview_messages')
    with op.batch_alter_table('skill_memory_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_memory_entries_step_key'))
        batch_op.drop_index(batch_op.f('ix_skill_memory_entries_status'))
        batch_op.drop_index(batch_op.f('ix_skill_memory_entries_skill_id'))
        batch_op.drop_index(batch_op.f('ix_skill_memory_entries_kind'))

    op.drop_table('skill_memory_entries')
    with op.batch_alter_table('knowledge_docs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_docs_skill_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_docs_project_id'))

    op.drop_table('knowledge_docs')
    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_sessions_skill_id'))
        batch_op.drop_index(batch_op.f('ix_interview_sessions_project_id'))

    op.drop_table('interview_sessions')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_project_id'))

    op.drop_table('skills')
    with op.batch_alter_table('llm_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_providers_project_id'))

    op.drop_table('llm_providers')
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_sources_project_id'))

    op.drop_table('data_sources')
    with op.batch_alter_table('procedure_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procedure_steps_procedure_id'))

    op.drop_table('procedure_steps')
    with op.batch_alter_table('project_usage_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_usage_daily_project_id'))

    op.drop_table('project_usage_daily')
    with op.batch_alter_table('procedures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procedures_subject_id'))
        batch_op.drop_index(batch_op.f('ix_procedures_project_id'))
        batch_op.drop_index(batch_op.f('ix_procedures_kind'))

    op.drop_table('procedures')
    # ### end Alembic commands ###
