"""skill versions, steps, library

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-03 12:53:13.629816
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_components',
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('source', sa.JSON(), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('env_requirements', sa.JSON(), nullable=False),
    sa.Column('install', sa.JSON(), nullable=False),
    sa.Column('docs', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('added_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_library_components'))
    )
    with op.batch_alter_table('library_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_components_slug'), ['slug'], unique=True)

    op.create_table('skill_versions',
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('major', sa.Integer(), nullable=False),
    sa.Column('minor', sa.Integer(), nullable=False),
    sa.Column('patch', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('parent_version_id', sa.String(length=36), nullable=True),
    sa.Column('origin', sa.String(length=24), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('frontmatter', sa.JSON(), nullable=False),
    sa.Column('knowledge_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('memory_snapshot', sa.JSON(), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('validation_report', sa.JSON(), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=True),
    sa.Column('build_log', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('state_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current_draft', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_skill_versions_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_versions')),
    sa.UniqueConstraint('skill_id', 'version', name='uq_skill_version')
    )
    with op.batch_alter_table('skill_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_versions_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_versions_state'), ['state'], unique=False)

    op.create_table('skill_dependencies',
    sa.Column('skill_version_id', sa.String(length=36), nullable=False),
    sa.Column('component_slug', sa.String(length=80), nullable=False),
    sa.Column('version_constraint', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['skill_version_id'], ['skill_versions.id'], name=op.f('fk_skill_dependencies_skill_version_id_skill_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_dependencies')),
    sa.UniqueConstraint('skill_version_id', 'component_slug', name='uq_skill_dep')
    )
    with op.batch_alter_table('skill_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_dependencies_skill_version_id'), ['skill_version_id'], unique=False)

    op.create_table('step_definitions',
    sa.Column('skill_version_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('side_effects', sa.String(length=16), nullable=False),
    sa.Column('restore_strategy', sa.String(length=24), nullable=False),
    sa.Column('trial_mode', sa.String(length=16), nullable=False),
    sa.Column('requires_explicit_auth', sa.Boolean(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('outputs', sa.JSON(), nullable=False),
    sa.Column('data_source_refs', sa.JSON(), nullable=False),
    sa.Column('success_criteria', sa.Text(), nullable=True),
    sa.Column('failure_modes', sa.JSON(), nullable=False),
    sa.Column('network', sa.Boolean(), nullable=False),
    sa.Column('mcp_tool_name', sa.String(length=80), nullable=True),
    sa.Column('library_component_slug', sa.String(length=80), nullable=True),
    sa.Column('test_status', sa.String(length=16), nullable=False),
    sa.Column('confirmations_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['skill_version_id'], ['skill_versions.id'], name=op.f('fk_step_definitions_skill_version_id_skill_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_step_definitions')),
    sa.UniqueConstraint('skill_version_id', 'key', name='uq_step_key')
    )
    with op.batch_alter_table('step_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_step_definitions_skill_version_id'), ['skill_version_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('step_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_step_definitions_skill_version_id'))

    op.drop_table('step_definitions')
    with op.batch_alter_table('skill_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_dependencies_skill_version_id'))

    op.drop_table('skill_dependencies')
    with op.batch_alter_table('skill_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_versions_state'))
        batch_op.drop_index(batch_op.f('ix_skill_versions_skill_id'))

    op.drop_table('skill_versions')
    with op.batch_alter_table('library_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_components_slug'))

    op.drop_table('library_components')
    # ### end Alembic commands ###
