"""trials, runs, checkpoints, discussions

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-03 13:07:26.722025
"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('skill_version_id', sa.String(length=36), nullable=True),
    sa.Column('skill_version', sa.String(length=32), nullable=True),
    sa.Column('trial_session_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('agent_target', sa.String(length=32), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('installation_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('api_key_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('inputs_summary', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('llm_usage', sa.JSON(), nullable=False),
    sa.Column('human_feedback', sa.String(length=16), nullable=True),
    sa.Column('is_golden', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs'))
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_skill_version_id'), ['skill_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_trial_session_id'), ['trial_session_id'], unique=False)

    op.create_table('step_discussions',
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('skill_version_id', sa.String(length=36), nullable=False),
    sa.Column('trial_session_id', sa.String(length=36), nullable=True),
    sa.Column('checkpoint_id', sa.String(length=36), nullable=True),
    sa.Column('step_key', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('outcome', sa.JSON(), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_step_discussions'))
    )
    with op.batch_alter_table('step_discussions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_step_discussions_checkpoint_id'), ['checkpoint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_discussions_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_discussions_skill_version_id'), ['skill_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_discussions_trial_session_id'), ['trial_session_id'], unique=False)

    op.create_table('checkpoints',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('trial_session_id', sa.String(length=36), nullable=True),
    sa.Column('step_key', sa.String(length=64), nullable=False),
    sa.Column('phase', sa.String(length=16), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('execution_mode', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('proposal', sa.JSON(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('correction_text', sa.Text(), nullable=True),
    sa.Column('updated_instructions', sa.Text(), nullable=True),
    sa.Column('confirmation_token', sa.String(length=64), nullable=True),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_checkpoints_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkpoints'))
    )
    with op.batch_alter_table('checkpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkpoints_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkpoints_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkpoints_trial_session_id'), ['trial_session_id'], unique=False)

    op.create_table('run_annotations',
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('run_step_id', sa.String(length=36), nullable=True),
    sa.Column('skill_id', sa.String(length=36), nullable=True),
    sa.Column('step_key', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_run_annotations_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_annotations'))
    )
    with op.batch_alter_table('run_annotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_annotations_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_annotations_skill_id'), ['skill_id'], unique=False)

    op.create_table('run_steps',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('step_key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('execution_mode', sa.String(length=16), nullable=True),
    sa.Column('proposed_action', sa.JSON(), nullable=True),
    sa.Column('executed_action', sa.JSON(), nullable=True),
    sa.Column('human_correction', sa.JSON(), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('outputs', sa.JSON(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('tool_name', sa.String(length=120), nullable=True),
    sa.Column('llm_usage', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_run_steps_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_steps'))
    )
    with op.batch_alter_table('run_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_steps_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_steps_run_id'), ['run_id'], unique=False)

    op.create_table('trial_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('skill_version_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('target_agent', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('build', sa.Integer(), nullable=False),
    sa.Column('install_manifest', sa.JSON(), nullable=False),
    sa.Column('current_step_key', sa.String(length=64), nullable=True),
    sa.Column('current_iteration', sa.Integer(), nullable=False),
    sa.Column('corrections', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('keep_installed', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_trial_sessions_skill_id_skills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_version_id'], ['skill_versions.id'], name=op.f('fk_trial_sessions_skill_version_id_skill_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trial_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trial_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_trial_sessions_token_hash'))
    )
    with op.batch_alter_table('trial_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trial_sessions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trial_sessions_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trial_sessions_skill_version_id'), ['skill_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trial_sessions_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_trial_sessions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('skill_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('draft_spec', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('build', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill_versions', schema=None) as batch_op:
        batch_op.drop_column('build')
        batch_op.drop_column('draft_spec')

    with op.batch_alter_table('trial_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trial_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_trial_sessions_state'))
        batch_op.drop_index(batch_op.f('ix_trial_sessions_skill_version_id'))
        batch_op.drop_index(batch_op.f('ix_trial_sessions_skill_id'))
        batch_op.drop_index(batch_op.f('ix_trial_sessions_project_id'))

    op.drop_table('trial_sessions')
    with op.batch_alter_table('run_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_steps_run_id'))
        batch_op.drop_index(batch_op.f('ix_run_steps_idempotency_key'))

    op.drop_table('run_steps')
    with op.batch_alter_table('run_annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_annotations_skill_id'))
        batch_op.drop_index(batch_op.f('ix_run_annotations_run_id'))

    op.drop_table('run_annotations')
    with op.batch_alter_table('checkpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkpoints_trial_session_id'))
        batch_op.drop_index(batch_op.f('ix_checkpoints_state'))
        batch_op.drop_index(batch_op.f('ix_checkpoints_run_id'))

    op.drop_table('checkpoints')
    with op.batch_alter_table('step_discussions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_step_discussions_trial_session_id'))
        batch_op.drop_index(batch_op.f('ix_step_discussions_skill_version_id'))
        batch_op.drop_index(batch_op.f('ix_step_discussions_skill_id'))
        batch_op.drop_index(batch_op.f('ix_step_discussions_checkpoint_id'))

    op.drop_table('step_discussions')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_trial_session_id'))
        batch_op.drop_index(batch_op.f('ix_runs_status'))
        batch_op.drop_index(batch_op.f('ix_runs_skill_version_id'))
        batch_op.drop_index(batch_op.f('ix_runs_skill_id'))
        batch_op.drop_index(batch_op.f('ix_runs_project_id'))

    op.drop_table('runs')
    # ### end Alembic commands ###
