"""review, authorizations, transitions

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-03 13:24:09.057319
"""
from alembic import op
import sqlalchemy as sa


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorizations',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=True),
    sa.Column('decided_by', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('checklist', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authorizations'))
    )
    with op.batch_alter_table('authorizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authorizations_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_authorizations_subject_id'), ['subject_id'], unique=False)

    op.create_table('review_requests',
    sa.Column('skill_version_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('mcp_server_version_id', sa.String(length=36), nullable=True),
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('assignee_id', sa.String(length=36), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('checklist', sa.JSON(), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['skill_version_id'], ['skill_versions.id'], name=op.f('fk_review_requests_skill_version_id_skill_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_requests'))
    )
    with op.batch_alter_table('review_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_requests_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_requests_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_requests_skill_version_id'), ['skill_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_requests_state'), ['state'], unique=False)

    op.create_table('version_transitions',
    sa.Column('skill_version_id', sa.String(length=36), nullable=False),
    sa.Column('from_state', sa.String(length=32), nullable=False),
    sa.Column('to_state', sa.String(length=32), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('authorization_id', sa.String(length=36), nullable=True),
    sa.Column('review_decision_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['skill_version_id'], ['skill_versions.id'], name=op.f('fk_version_transitions_skill_version_id_skill_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_version_transitions'))
    )
    with op.batch_alter_table('version_transitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_version_transitions_skill_version_id'), ['skill_version_id'], unique=False)

    op.create_table('review_decisions',
    sa.Column('review_request_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=24), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('file_comments', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['review_request_id'], ['review_requests.id'], name=op.f('fk_review_decisions_review_request_id_review_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_decisions'))
    )
    with op.batch_alter_table('review_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_decisions_review_request_id'), ['review_request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_decisions_review_request_id'))

    op.drop_table('review_decisions')
    with op.batch_alter_table('version_transitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_version_transitions_skill_version_id'))

    op.drop_table('version_transitions')
    with op.batch_alter_table('review_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_requests_state'))
        batch_op.drop_index(batch_op.f('ix_review_requests_skill_version_id'))
        batch_op.drop_index(batch_op.f('ix_review_requests_skill_id'))
        batch_op.drop_index(batch_op.f('ix_review_requests_project_id'))

    op.drop_table('review_requests')
    with op.batch_alter_table('authorizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authorizations_subject_id'))
        batch_op.drop_index(batch_op.f('ix_authorizations_project_id'))

    op.drop_table('authorizations')
    # ### end Alembic commands ###
