"""mcp servers

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-03 13:46:11.963299
"""
from alembic import op
import sqlalchemy as sa


revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_servers',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('runtime', sa.String(length=24), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_mcp_servers_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mcp_servers')),
    sa.UniqueConstraint('skill_id', name='uq_mcp_server_skill')
    )
    with op.batch_alter_table('mcp_servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_servers_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_servers_skill_id'), ['skill_id'], unique=False)

    op.create_table('mcp_server_versions',
    sa.Column('mcp_server_id', sa.String(length=36), nullable=False),
    sa.Column('skill_version_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('env_requirements', sa.JSON(), nullable=False),
    sa.Column('dependencies', sa.JSON(), nullable=False),
    sa.Column('draft_spec', sa.JSON(), nullable=True),
    sa.Column('build_log', sa.Text(), nullable=True),
    sa.Column('static_report', sa.JSON(), nullable=False),
    sa.Column('trial_report', sa.JSON(), nullable=True),
    sa.Column('build', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['mcp_servers.id'], name=op.f('fk_mcp_server_versions_mcp_server_id_mcp_servers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_version_id'], ['skill_versions.id'], name=op.f('fk_mcp_server_versions_skill_version_id_skill_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mcp_server_versions')),
    sa.UniqueConstraint('skill_version_id', name='uq_mcp_version_skill_version')
    )
    with op.batch_alter_table('mcp_server_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_server_versions_mcp_server_id'), ['mcp_server_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_server_versions_skill_version_id'), ['skill_version_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcp_server_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_server_versions_skill_version_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_server_versions_mcp_server_id'))

    op.drop_table('mcp_server_versions')
    with op.batch_alter_table('mcp_servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_servers_skill_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_servers_project_id'))

    op.drop_table('mcp_servers')
    # ### end Alembic commands ###
