"""improvement proposals

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-03 14:02:40.487376
"""
from alembic import op
import sqlalchemy as sa


revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('improvement_proposals',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('base_version_id', sa.String(length=36), nullable=False),
    sa.Column('proposed_version_id', sa.String(length=36), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('source_run_ids', sa.JSON(), nullable=False),
    sa.Column('source_issue_ids', sa.JSON(), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('diff_summary', sa.JSON(), nullable=False),
    sa.Column('golden_pass_rate', sa.Float(), nullable=True),
    sa.Column('requested_by', sa.String(length=36), nullable=True),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_comment', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_improvement_proposals_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_improvement_proposals'))
    )
    with op.batch_alter_table('improvement_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_improvement_proposals_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_improvement_proposals_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_improvement_proposals_state'), ['state'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('improvement_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_improvement_proposals_state'))
        batch_op.drop_index(batch_op.f('ix_improvement_proposals_skill_id'))
        batch_op.drop_index(batch_op.f('ix_improvement_proposals_project_id'))

    op.drop_table('improvement_proposals')
    # ### end Alembic commands ###
