"""Turn an McpSpec into the files of a small Python MCP server package (code owns the structure)."""

from __future__ import annotations

import json
import re

from autoskill.services.mcpgen.spec import McpSpec, McpTool

JSON_TYPES = {
    "string": "str",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
    "array": "list",
    "object": "dict",
}


def package_name(server_name: str) -> str:
    return re.sub(r"[^a-z0-9_]", "_", server_name.lower())


def input_schema(tool: McpTool) -> dict:
    props = {p.name: {"type": p.type, "description": p.description} for p in tool.params}
    required = [p.name for p in tool.params if p.required]
    if tool.side_effects != "read_only":
        props["dry_run"] = {
            "type": "boolean",
            "description": "When true (default) describe the effect without applying it.",
            "default": True,
        }
    if tool.side_effects == "irreversible":
        props["confirmation_token"] = {
            "type": "string",
            "description": "Token minted by AutoSkill when the person authorized real execution.",
        }
    return {"type": "object", "properties": props, "required": required}


def _signature(tool: McpTool) -> str:
    parts = []
    for p in tool.params:
        typ = JSON_TYPES[p.type]
        if p.required:
            parts.append(f"{p.name}: {typ}")
        else:
            parts.append(f"{p.name}: {typ} | None = {json.dumps(p.default) if p.default is not None else 'None'}")
    if tool.side_effects != "read_only":
        parts.append("dry_run: bool = True")
    if tool.side_effects == "irreversible":
        parts.append("confirmation_token: str | None = None")
    return ", ".join(parts)


def _kwargs(tool: McpTool) -> str:
    names = [p.name for p in tool.params]
    if tool.side_effects != "read_only":
        names.append("dry_run")
    if tool.side_effects == "irreversible":
        names.append("confirmation_token")
    return ", ".join(f"{n}={n}" for n in names)


def render_tool_module(tool: McpTool) -> str:
    header = f'''"""Tool `{tool.name}` for step `{tool.step_key}` ({tool.side_effects}).

{tool.description}
Generated by AutoSkill; the body below was written by the author model and passed static checks.
"""

from __future__ import annotations

'''
    guard = ""
    if tool.side_effects == "irreversible":
        guard = '''

def _require_confirmation(kwargs: dict) -> None:
    """Irreversible effect: refuse without the confirmation token minted by AutoSkill."""
    if kwargs.get("dry_run", True):
        return
    if not kwargs.get("confirmation_token"):
        raise PermissionError("irreversible action: confirmation_token required (authorize it in AutoSkill first)")
'''
    body = tool.code.strip("\n") + "\n"
    return header + guard + "\n" + body


def render_server(server_name: str, spec: McpSpec, tools: list[McpTool]) -> str:
    pkg = package_name(server_name)
    registrations = []
    for tool in tools:
        guard = ""
        if tool.side_effects == "irreversible":
            guard = "\n    _mod._require_confirmation(dict(dry_run=dry_run, confirmation_token=confirmation_token))"
        registrations.append(
            f'\n\n@mcp.tool(name="{tool.name}", description={json.dumps(tool.description)})\n'
            f"def {tool.name}({_signature(tool)}) -> dict:\n"
            f"    from {pkg}.tools import {tool.name} as _mod{guard}\n"
            f"    return _mod.run({_kwargs(tool)})"
        )
    tools_json = json.dumps([{"name": t.name, "step_key": t.step_key, "side_effects": t.side_effects} for t in tools])
    header = (
        f'"""{server_name}: MCP server generated by AutoSkill.\n\n{spec.description}\n'
        f"Run with `{server_name}` (stdio). `{server_name} --list-tools` prints the tool list as JSON (used by\n"
        "`autoskill mcp check`). Tools with side effects default to dry_run=True; irreversible tools require a\n"
        'confirmation token authorized in AutoSkill.\n"""\n'
    )
    body = (
        "\nfrom __future__ import annotations\n\nimport json\nimport sys\n\n"
        "try:  # mcp SDK 2.x\n    from mcp.server.mcpserver import MCPServer as _Server\n"
        "except ImportError:  # mcp SDK 1.x\n"
        "    from mcp.server.fastmcp import FastMCP as _Server  # type: ignore[no-redef]\n\n"
        f'mcp = _Server("{server_name}", instructions={json.dumps(spec.description)})\n'
        + "".join(registrations)
        + f"\n\n\nTOOLS = {tools_json}\n\n\n"
        'def main() -> None:\n    if "--list-tools" in sys.argv:\n        print(json.dumps(TOOLS))\n        return\n'
        '    mcp.run(transport="stdio")\n\n\nif __name__ == "__main__":\n    main()\n'
    )
    return header + body


def render_pyproject(server_name: str, spec: McpSpec, version: str) -> str:
    pkg = package_name(server_name)
    deps = ["mcp>=1.2", *sorted(set(spec.dependencies))]
    dep_lines = ",\n".join(f'    "{d}"' for d in deps)
    return f'''[project]
name = "{server_name}"
version = "{version}"
description = {json.dumps(spec.description[:200])}
requires-python = ">=3.11"
dependencies = [
{dep_lines}
]

[project.scripts]
{server_name} = "{pkg}.server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["{pkg}"]
'''


def render_readme(server_name: str, spec: McpSpec, tools: list[McpTool]) -> str:
    lines = [f"# {server_name}", "", spec.description, "", "## Tools", ""]
    for t in tools:
        lines.append(f"- `{t.name}` (step `{t.step_key}`, {t.side_effects}): {t.description}")
    if spec.env_requirements:
        lines += ["", "## Environment", ""]
        for e in spec.env_requirements:
            lines.append(f"- `{e.name}`: {e.description}{' (secret)' if e.secret else ''}")
    lines += [
        "",
        "## Install",
        "",
        "```bash",
        f"pipx install ./mcp/{server_name}",
        f"{server_name} --list-tools",
        "```",
        "",
    ]
    if spec.notes:
        lines += ["## Notes", "", spec.notes, ""]
    return "\n".join(lines)


def render_tests(server_name: str, tools: list[McpTool]) -> str:
    pkg = package_name(server_name)
    checks = "\n".join(f"    from {pkg}.tools import {t.name}\n    assert callable({t.name}.run)" for t in tools)
    return f'''"""Smoke tests generated by AutoSkill: every tool module imports and exposes run()."""


def test_tools_import():
{checks}


def test_server_lists_tools():
    from {pkg} import server

    assert len(server.TOOLS) == {len(tools)}
'''


def assemble_mcp(server_name: str, version: str, spec: McpSpec) -> dict[str, bytes]:
    pkg = package_name(server_name)
    files: dict[str, bytes] = {
        "pyproject.toml": render_pyproject(server_name, spec, version).encode(),
        "README.md": render_readme(server_name, spec, spec.tools).encode(),
        ".env.example": ("\n".join(f"{e.name}=" for e in spec.env_requirements) + "\n").encode(),
        f"{pkg}/__init__.py": f'"""{server_name} generated by AutoSkill."""\n'.encode(),
        f"{pkg}/server.py": render_server(server_name, spec, spec.tools).encode(),
        f"{pkg}/tools/__init__.py": b"",
        "tests/test_tools.py": render_tests(server_name, spec.tools).encode(),
    }
    for tool in spec.tools:
        files[f"{pkg}/tools/{tool.name}.py"] = render_tool_module(tool).encode()
    return files
